### ISSUE TITLE
[Bug]: Diet sats rendering under Quark inventory filter button

### ISSUE THREAD

**Issue by p1ut0nium-git** [TheIllusiveC4/Diet#101]
### What happened?

When hovering over the Diet button in the inventory UI, it renders under the Quark item sort button.

![2021-12-01_18 11 46](https://user-images.githubusercontent.com/60378380/144335014-8e9d0554-59c9-4a7b-bc4d-f2b684a64f32.png)

### How do you trigger this bug?

1. open inventory.
2. hover over diet button.

### Forge Version

36.2.9

### Mod Version

diet-forge-1.16.5-1.0.1.1

### Other Relevant Mod Versions

Quark version: Quark-r2.4-319

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this issue, testing Diet with Quark shows the tooltip rendering over the button as expected. Are you able to reproduce this with only Diet and Quark installed? If not, then it is a mod conflict and that mod will have to be identified first.

**Comment by xmsteele23** [comment]
I’m having a similar issue in 1.18.2 where when I click on the diet drumstick in my inventory BYG’s inventory biomepedia opens instead. Also when hovering over it the only text shown is BYG biomepedia
