### ISSUE TITLE
[Bug]: Bread without Food Group

### ISSUE THREAD

**Issue by StrangerSon71** [TheIllusiveC4/Diet#106]
### What happened?

Bread doesn't have Grains.

### How do you trigger this bug?

1. Look at Bread tooltip.

### Forge Version

36.2.20

### Mod Version

1.16.5 1.0.2.0

**Comment by TheIllusiveC4** [comment]
I can't reproduce this, Bread has grains in my testing environment. Can you reproduce this with only Diet installed? And with default configs/tags?

**Comment by StrangerSon71** [comment]
Hmm, I can't either. Modlist is [here](https://www.curseforge.com/minecraft/modpacks/strangely-modded/relations/dependencies), I'll probably isolate it later.

**Comment by mpevner** [comment]
Amusingly, I do have this issue as well. I'll try to generate a modlist later and see if any of it matches up with yours.
edit: list as follows
appleskin
better advancements
blueprint
bountiful
cavebiomeapi
caves cliffs backport
citadel
configured
create
create crafts
curious api
diet
farmers delight
farmers delight compat
farmers tea
fast leaf decay
fastfurnace
fastworkbench
flywheel
ice and fire
jei
jer
kotlin
minecolonies
mouse tweaks
nethers delight
placebo
quark
simply tea
structurize
twilight forest
toast control
yungs api, better dungeon, mineshaft, stronghold, bridges

**Comment by mpevner** [comment]
I have managed to validate and isolate this issue to Minecolonies. The following mods and versions were used for 1.16.5:
Diet 1.0.2.1
Structurize 0.13.252
Minecolonies 1.0.309

**Comment by StrangerSon71** [comment]
Thank you! Sorry to dev for not doing this myself.
