### ISSUE TITLE
[Bug]:  If hunger bar is full, consuming an item with sugar or what not does not add to the meter

### ISSUE THREAD

**Issue by zachsai** [TheIllusiveC4/Diet#109]
### What happened?

https://streamable.com/4b1jt0
You can see in the video what I mean

### How do you trigger this bug?

1.Install Croptopia & Diet
2.Consume a drink when hunger bar is full
3.Check meter not go up
...

### Forge Version

39.0.46

### Mod Version

1.18.1-1.2.0.0

**Comment by TheIllusiveC4** [comment]
This is intentional. If Diet values could be increased even when your hunger bar is full, it would be easy to just spam certain foods and max out all of them in one sitting.

**Comment by zachsai** [comment]
Would it be possible for you to add a toggle to allow this? Also, I was having trouble with the effects, posted about it in your discord as "WelpStudent" if you get a chance to look at it, that would be great :D

**Comment by TheIllusiveC4** [comment]
I've already responded to you on Discord.

Although I'm usually open to weird configs, I'm kinda reluctant to add this one as a toggle. This kind of thing really would just trivialize the whole Diet system, to the point where you are potentially just giving people free buffs essentially.
