### ISSUE TITLE
[Question]: Localized name for new food group

### ISSUE THREAD

**Issue by Baakshi** [TheIllusiveC4/Diet#117]
### What is the new feature or improvement?

In the wiki for Customizing Food Groups, you have section called "Localization" where you explain how to give a custom food group its translation. I just can't seem to figure out where exactly you have to put the Translation. Can you tell emw here it needs to be put?

**Comment by TheIllusiveC4** [comment]
You make a new resource pack and include it as a language key. For more information on Resource Packs, specifically language files, please see the Minecraft wiki: https://minecraft.fandom.com/wiki/Resource_Pack#Language
