### ISSUE TITLE
is this correct? 

### ISSUE THREAD

**Issue by ThePetePandaPablo** [TheIllusiveC4/Diet#121]
### What is the new feature or improvement?

[[groups]]
	color = "#d4781c"
	decay_multiplier = 1.0
	beneficial = true
        name = "groups.diet.fire.name"                           <---here
	icon = "minecraft:cooked_beef"
	gain_multiplier = 1.0
	default_value = 0.0
	order = 0

**Comment by TheIllusiveC4** [comment]
No, it seems you're trying to use the whole language key as the name, which is incorrect. It only needs to be `name = "fire"`, if you wanted your group's identifier to be "fire".

**Comment by ThePetePandaPablo** [comment]
Sadly when I did that the game crashes and I get the error Tag diet:fire used before it was bound

**Comment by TheIllusiveC4** [comment]
It's because you're creating a food group with no foods. Add some food items to the `diet:fire` item tag and that error will go away.

**Comment by ThePetePandaPablo** [comment]
Omg I did not add the "" xD Thanks <3
