### ISSUE TITLE
[Bug]: Crash on world joining

### ISSUE THREAD

**Issue by ekiplier** [TheIllusiveC4/Diet#123]
### What happened?

my modpack crashes every time I try creating or joining a world with diet installed. It didn't use to do that, but I haven't tried any earlier versions of Diet since I last updated it on the CurseForge launcher. 

### How do you trigger this bug?

1. Install diet
2. create new/join world
3. see crash
...

### Forge Version

Forge - 36.2.33

### Mod Version

diet-forge-1.16.5-1.0.3.0

### Other Relevant Mod Versions

My modpack has many other mods installed so this might be some compatibility issue. Hopefully, the crash report has enough info to figure out the problem.

### Relevant Log Outputs

https://gist.github.com/ekiplier/becd1c3c065a86cece7867e0e3d8a360

**Comment by TheIllusiveC4** [comment]
Should be fixed in 1.0.3.1.
