### ISSUE TITLE
[Bug]: Bread in fruit group

### ISSUE THREAD

**Issue by ChromaPIE** [TheIllusiveC4/Diet#126]
### What happened?

1.16.5, Bread increases Fruit by 8.5, which makes zero sense.

It's far too hilarious and nobody ever reported that so I'm wondering if any 3rd party mods was to be blamed.

### How do you trigger this bug?

Simply check vanilla bread's tooltips.

### Forge Version

Not related

### Mod Version

1.16.5-1.0.3.0

### Other Relevant Mod Versions

https://www.toptal.com/developers/hastebin/usewitunos.rb

Here's a recent **unrelated** crash report, containing the exact modlist.

### Relevant Log Outputs

N/A

**Comment by TheIllusiveC4** [comment]
This is not the case in an environment with only Diet installed, so it's likely a rather specific mod interaction. Bread isn't specifically defined, it gets its food groups from Wheat actually. Can you check the recipes for JEI and see if there are any alternate recipes for Bread that could be giving it a new food group?

If you can't figure out where the issue may be coming from, then you can also run the `/diet export trails` command and then share the `diet.csv` file that gets generated in your `logs` folder. I'll probably be able to figure it out from there.

**Comment by ChromaPIE** [comment]
Oh yea it's Pam's Harvestcraft. It provides a recipe to craft a bread using three breadfruits, under `#diet:fruits` group. This explains the issue. So how can I overwrite the bread's group and value?

**Comment by TheIllusiveC4** [comment]
You don't have to worry about it, I'll add bread to the proper tag in the mod itself which should resolve this issue.
