### ISSUE TITLE
[Bug]: Loading world crashes

### ISSUE THREAD

**Issue by Dr-WeiAL** [TheIllusiveC4/Diet#127]
### What happened?

After I add a Diet, loading an existing or newly created world crashes

### How do you trigger this bug?

1.Install Diet
2.Load the world

### Forge Version

forge 40.0.49

### Mod Version

Diet 1.18.2 1.3.0.0

### Other Relevant Mod Versions

culinaryconstruct 1.18.2 4.3.0.0

**Comment by TheIllusiveC4** [comment]
Please include the crash report.

**Comment by Dr-WeiAL** [comment]
> Please include the crash report.
[crash-2022-04-16_18.57.37-client.txt](https://github.com/TheIllusiveC4/Diet/files/8500768/crash-2022-04-16_18.57.37-client.txt)
[crash-2022-04-16_18.57.34-server.txt](https://github.com/TheIllusiveC4/Diet/files/8500772/crash-2022-04-16_18.57.34-server.txt)

**Comment by Dr-WeiAL** [comment]
Do I need to upload anything else?
