### ISSUE TITLE
[Request] Mod Support

### ISSUE THREAD

**Issue by Minothilos** [TheIllusiveC4/Diet#13]
- Environmental [https://www.curseforge.com/minecraft/mc-mods/environmental](url)
- Abnormals Delight [https://www.curseforge.com/minecraft/mc-mods/abnormals-delight](url)
- Creatures and Beasts [https://www.curseforge.com/minecraft/mc-mods/creatures-and-beasts](url)
- Better Default Biomes [https://www.curseforge.com/minecraft/mc-mods/better-default-biomes](url)
Thanks!

**Comment by Minothilos** [comment]
Hi I just realised. Neapolitan had a big update a day ago that adds multiple new food items. Should have thought of this before publishing the list but if this isn't already in it would be nice to have those items in the next update. Same goes for supplementaries (althought there it's just stackable pancakes, similar to atumnity)

**Comment by TheIllusiveC4** [comment]
Someone else already brought up the Neapolitan update, it's included already in the most recent update.

Supplementaries I'll have to take a look at though.

**Comment by Minothilos** [comment]
Thanks you!
