### ISSUE TITLE
[Feature]: Eat and raise nutrition when players are not hungry

### ISSUE THREAD

**Issue by LouiseWhite212109** [TheIllusiveC4/Diet#133]
### What is the new feature or improvement?

What a pity to meet with this mod so late!  It forces me to pay more attention to the variety of foods and thus improves the game's fun.
However, while playing Minecraft with this mod, I noticed that I can not eat when not hungry. It is so disappointing that I have to jump down from high above or step on a campfire to take another bite. Still, it takes a lot of time to raise all the 5 nutritions to over 80%.
I tried to use another mod (Always eat Reload) to overcome this shortcoming but, sadly, eating foods when not hungry does not cause any raise in nutrition.  I still have to make extra effort to make myself hungry.
Is there any possibility to add a changeable setting that whether players could EAT and RAISE nutrition even if they are not hungry? 
Finally, thanks a lot for providing such an amazing mod for all the players, including me!
P.S. a bug fix request is also proposed in another issue.

**Comment by TheIllusiveC4** [comment]
People have asked this quite a bit, but do you realize what you're asking for? Being able to raise your food group levels without being hindered by your hunger rate means that a player can simply sit around and spam food until they max out all of their food groups. It breaks the balance of the mod in a pretty major way.

It's not a definite no, but it would be a very problematic config option from a balance perspective and I'd need to hear a decent argument for its inclusion with that in mind.

**Comment by LouiseWhite212109** [comment]
Thanks for your attention. I now know what you think while designing this mod. Balance is genuinely worth considering.
