### ISSUE TITLE
[Bug]: Percentage display dislocation while using unicode

### ISSUE THREAD

**Issue by LouiseWhite212109** [TheIllusiveC4/Diet#134]
### What happened?

I noticed that a shell is applied outside the colored numbers to improve the visibility. Good design indeed. However, when I use Unicode in Language the shell seems to be dislocated (as it is in the picture).
It may be not an essential bug. I think it would be nice for players with various needs if you fix this bug. I am fully aware that making a wonderful mod as this has already taken a lot of effort of the author, so if your think it is not worthy to deal with, I will absolutely understand. 

### How do you trigger this bug?

1.just use unicode
2.
3.
...

### Forge Version

Forge 40.1.25

### Mod Version

diet-forge-1.18.2-1.3.1.0

**Comment by LouiseWhite212109** [comment]
![)@ 2)I~6$_D4R6KB@{HG` B](https://user-images.githubusercontent.com/90058062/172166591-5f6ceeaf-722a-447d-9bb7-5beb7af08619.png)

**Comment by TheIllusiveC4** [comment]
While I'd like to fix this, I'm not sure if I can based on Minecraft's own font rendering system. For instance, I tested this and the level counter on the experience bar (which is what the Diet's percentage numbers are based on design-wise) also suffers from this effect. It might be best to actually report this to Mojang themselves to fix in Minecraft.
