### ISSUE TITLE
[Five Food Groups]: A compatibility 

### ISSUE THREAD

**Issue by WhiteNoizzTeeVee** [TheIllusiveC4/Diet#136]
### If applicable, which other mod(s) is/are involved in your request?

[Drunken Mug](https://www.curseforge.com/minecraft/mc-mods/drunken-mug)

### What is the new support or change you're requesting?

I'm requesting that drinks from this mod could be added into one of five food categories.

**Comment by TheIllusiveC4** [comment]
I loaded up the mod and it already does have food groups. Are you seeing something different with the latest versions of the mods?
