### ISSUE TITLE
[Five Food Groups]: Corn Delight Support

### ISSUE THREAD

**Issue by Spiderach** [TheIllusiveC4/Diet#140]
### If applicable, which other mod(s) is/are involved in your request?

[Corn Delight](https://www.curseforge.com/minecraft/mc-mods/corn-delight)

### What is the new support or change you're requesting?

There is partial support due to other ingredients being mixed in, but the base corn itself doesn't have associated values. I would suggest grains, but vegetables or both would also be reasonable.

In addition, why are potatoes vegetables when they're all carbs? is it a taxonomical thing?

Maize - corn_delight:corn
Corn Kernel - corn_delight:corn_seeds
Grilled Corn - corn_delight:grilled_corn
Boiled Corn - corn_delight:boiled_corn
Popcorn - corn_delight:popcorn
Caramel Popcorn - corn_delight:caramel_popcorn
Corn Soup - corn_delight:corn_soup
Creamed Corn - corn_delight:creamed_corn
Creamy Corn Drink - corn_delight:creamy_corn_drink
Cornbread Batter - corn_delight:cornbread_batter
Cornbread - corn_delight:cornbread
Corn Dog - corn_delight:corn_dog
Classic Corn Dog - corn_delight:classic_corn_dog
Raw Tortilla - corn_delight:raw_tortilla
Tortilla - corn_delight:tortilla
Taco - corn_delight:taco
Cornbread Stuffing - corn_delight:cornbread_stuffing
Tortilla Chip - corn_delight:tortilla_chip
Nachos - corn_delight:nachos_block
Nachos - corn_delight:nachos_bowl
Popcorn Bucket - corn_delight:popcorn_box

**Comment by TheIllusiveC4** [comment]
> In addition, why are potatoes vegetables when they're all carbs? is it a taxonomical thing?

They're a root vegetable. Classifications are based mainly on taxonomy rather than nutrition, but it mainly comes down to what would make the most sense to most users and what other mods use as classification.
