### ISSUE TITLE
[Feature]: any plan on 1.19.X ?

### ISSUE THREAD

**Issue by tomto0810** [TheIllusiveC4/Diet#142]
### What is the new feature or improvement?

Just waiting, just want to know a general time period

**Comment by colinxu2020** [comment]
@TheIllusiveC4 Any Plan For 1.19.X?

**Comment by TheIllusiveC4** [comment]
Yes, it will come eventually. But no estimates at this time.

**Comment by colinxu2020** [comment]
Ok, thanks for making this extractly good mod!

**Comment by TheIllusiveC4** [comment]
Diet for 1.19.2 has now been published.
