### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by iseal56** [TheIllusiveC4/Diet#150]
### Minecraft Version

1.16.5

### What happened?

Started the server and the mod thew an error

### How do you trigger this bug?

1.Install the mod
2. Start the server

### Loader

Forge

### Loader Version

Forge 36.2.39

### API Version

N/A

### Mod Version

1.0.4.1

### Relevant Log Outputs

https://pastebin.com/52c76q40

**Comment by TheIllusiveC4** [comment]
Looks like it may be an improper tag configuration. Did you try to configure the mod in any way or is this part of a modpack that has a custom configuration?

**Comment by iseal56** [comment]
Part of a modpack, the modpack is "light in the sky", do you want the config?

**Comment by TheIllusiveC4** [comment]
Does it crash in single player or only when starting a server?

**Comment by iseal56** [comment]
I've only started the server yet, I'm going to try starting the client, give me a second

**Comment by iseal56** [comment]
No, it does not crash on singleplayer. Even when creating a world it works

**Comment by TheIllusiveC4** [comment]
Unfortunately I cannot reproduce this, even on a server with the modpack you mentioned. I started the server and it did not crash, as expected. Are you sure you did not change anything from the defaults?

Please share your full crash log.
