### ISSUE TITLE
[Bug]: The config file in serverconfig is missing

### ISSUE THREAD

**Issue by uitstalie** [TheIllusiveC4/Diet#152]
### Minecraft Version

1.19.2

### What happened?

It seems that the config file that was supposed to be generated in serverconfig is not generated, is this a bug/feature? Or has the location of these files changed? Or is the wiki out of date?

note that Diet had been successfully loaded and datapack written by myself worked fine.

### How do you trigger this bug?

1.open minecraft
2.create a new world
3.check the serverconfig file
...

### Loader

Fabric

### Loader Version

forge 43.2.14

### Mod Version

diet-forge-2.0.0-beta+1.19.2

**Comment by TheIllusiveC4** [comment]
The GitHub wiki is out of date, it's for 1.18.2 and below. For 1.19.2 and above, the config files are all in the `config` folder. In addition, effects and groups configurations are now datapack-driven according to this:
https://docs.illusivesoulworks.com/category/diet
