### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GroovieSmoothie** [TheIllusiveC4/Diet#156]
### Minecraft Version

1.19.2

### What happened?

The configuration files "diet-groups.toml" and "diet-effects.toml" Don't exist.

### How do you trigger this bug?

I didn't trigger it, it just doesn't exist. :/

### Loader

Forge

### Loader Version

Forge 43.2.14

### Mod Version

 diet-forge-2.0.0+1.19.2.jar

**Comment by TheIllusiveC4** [comment]
Diet groups and effects, starting with 1.19.2, have moved to datapacks. More information here:
https://docs.illusivesoulworks.com/category/diet
