### ISSUE TITLE
[Bug]: Diet 2.1.0 for Fabric doesn't create diet-effects.toml and diet-groups.toml in serverconfig folder

### ISSUE THREAD

**Issue by teleheel** [TheIllusiveC4/Diet#159]
### Minecraft Version

1.20.1

### What happened?

The `diet-effects.toml` and `diet-groups.toml` files aren't created in the `serverconfig` folder when creating a new world. Not really sure whether they _should_ be created, or if the defaults are built into the mod. Either way, creating `diet-effects.toml` manually with the entry below doesn't override the default effect, as the Hunger effect gained in-game is still at level IV and not I as defined in the config file. 

```
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.movement_speed"
        operation = "multiply_base"
        amount = 0.25
    [[effects.status_effects]]
        name = "minecraft:hunger"
        power = 1
    [[effects.conditions]]
        groups = ["sugars"]
        match = "all"
        above = 0.8
        below = 1.0
``` 

### How do you trigger this bug?

1. Install the mod to a fresh Fabric instance.
2. Start the game and create a new world.
3. Check the world's `serverconfig` folder to see that no files have been created.
4. Give the player enough sugars to trigger the effect increasing movement speed and applying the hunger effect (e.g. by the `\diet add <player> sugars 1` command). 

### Loader

Fabric

### Loader Version

Fabric - 0.14.21

### API Version

Fabric API 0.86.1+1.20.1

### Mod Version

Diet 2.1.0+1.20.1

**Comment by b0b4444** [comment]
The config is in the config folder, and effects have to be made with datapacks
https://github.com/illusivesoulworks/diet/issues/152

For some reason they have not updated the github in all this time

**Comment by teleheel** [comment]
Ah okay, my bad for not checking the closed issues. Thanks!
