### ISSUE TITLE
[Bug]: 1.19.2 When generateGroupsForEmptyItems = false special foods are not used

### ISSUE THREAD

**Issue by Maypul** [TheIllusiveC4/Diet#170]
### Minecraft Version

1.19.2

### What happened?

When you use generateGroupsForEmptyItems = false  option, it seems some of the items you put in special_food.json are not applied correctly in game, for example a cake still shows + tooltip but pumpin does not even if both are added in the file.

### How do you trigger this bug?

1. Set generateGroupsForEmptyItems = false in Diet config
2. See in game that the tooltip for special foods is missing

### Loader

Forge

### Loader Version

43.2.21

### API Version

N/A

### Mod Version

2.0.1

### Relevant Log Outputs

https://prnt.sc/e6-ubdXi8KuW
https://prnt.sc/dWA_gscPN3Yl
https://prnt.sc/GxZhtFwdxxBa

**Comment by TheIllusiveC4** [comment]
Since this seems to have been closed, is this still an issue or has it been resolved as not a bug?
