### ISSUE TITLE
[Bug]: Torchberries from Twilight Forest are not being recognized when added to the config

### ISSUE THREAD

**Issue by Maypul** [TheIllusiveC4/Diet#172]
### Minecraft Version

1.19.2

### What happened?

I have added said torchberries to the fruit list but in-game item is not marked as "+Fruits". It's eatable item and also tried adding to special foods, no difference. I have checked the spelling and it's correct. It's literally the only item that is not being recognized in my whole game.

### How do you trigger this bug?

Add entry:
    {
      "id": "twilightforest:torchberries",
      "required": false
    },
to fruits.json
Open up game, and see food is not marked. It has also correct tags as diet:fruits

### Loader

Forge

### Loader Version

43.2.21

### Mod Version

2.0.1

**Comment by TheIllusiveC4** [comment]
> It's eatable item

I've tested this on my end and I've noticed that, while it's edible, it doesn't add any food values to the hunger bar. Foods that do not have a food value also do not have a corresponding diet value, since the latter is derived from the former.

**Comment by Maypul** [comment]
I must have missed that somehow, in this case I will add hunger values myself and report back. Thanks!

**Comment by Maypul** [comment]
Confirming, it's working as intended. I'm just blind. https://prnt.sc/wLMBPfmDQGzJ
