### ISSUE TITLE
Nutrition gain penalty not applying

### ISSUE THREAD

**Issue by Girithien** [TheIllusiveC4/Diet#18]
While having multiple groups of nutrients active at the same time the reduction to nutrition gain does not seem to apply.

Default config (fresh instance)
diet 1.16.5-0.13 
minecraft 1.16.5

gif showing how the full 10% from a steak still apply with 4 groups active: https://gyazo.com/dfcb94c1735b35ffd76e0caa194b1c75

**Comment by TheIllusiveC4** [comment]
The penalty to gain for multiple food groups refers to the item itself, not the number of active groups on the player. For instance, a food that has the same food level and saturation as steak but has both "Proteins" and "Grains" would have a lower combined gain than steak. And then the penalty applies cumulatively for every following food group. The ultimate effect is that foods that cover more food groups have progressively less total gain.
