### ISSUE TITLE
[Bug]: No Food, No Diet.

### ISSUE THREAD

**Issue by MinerB4** [TheIllusiveC4/Diet#183]
### Minecraft Version

1.20.1

### What happened?

I used a mod called "Classic Food" which disables Minecraft's hunger system, turns out directly healing health with food doesn't give Diet points.

### How do you trigger this bug?

1. _Reject 1.8b, become Hungerless_
2. Eat something with a Diet attribute
3. Non-profit

### Loader

Forge

### Loader Version

Forge - 47.2.17

### API Version

N/A

### Mod Version

2.1.1

**Comment by TheIllusiveC4** [comment]
This is working as intended as Diet's system functions off of the Minecraft hunger system. I'm workshopping some ways to separate them out so that Diet's system can exist on its own, but it'll require a lot of thought and potential reworks to accomplish before that happens.
