### ISSUE TITLE
Support for drinkables?

### ISSUE THREAD

**Issue by Sonanndes** [TheIllusiveC4/Diet#25]
Hi TheIllusiveC4, I created an additional  group "beverages" and tagged all drinkables as such. As far as items already got a value due to other default groups (i.e. simplytea:cup_of_*), it's working fine, but there were some drinkables left out, like minecraft:potion, (i.e. water bottle), minecraft:milk_bucket, farmersdelight:milk_bottle, farnersdelight:hot_cocoa etc.Could you please just give them nutrition values, even without tagging them in your default system, so everything digestible got a value on them and others can tag them?
Maybe in the future there could be a way to overide individual nutrition values of items in the config or even give different values per tag on multitagged items...
I like your mod a lot and I am trying to integrate it in my modpack in a way, that makes good eating behavior nescessary for the game.
Thanks for your great work!

**Comment by TheIllusiveC4** [comment]
Here's the issue: Drinkables like the ones you mentioned do not have a food value. This means that players can infinitely drink them and thus gain benefits without ever worrying about their diet values decaying. This breaks the balance of Diet in a somewhat tremendous way, so I do not plan to ever support items that do not provide a food value.

However, you're in luck, because if you really want to do this, there's a `foodOverride` option in the `diet-server.toml` config file that allows you to provide food quality values to items if necessary.

**Comment by Sonanndes** [comment]
Thanks, that will do the job, for in my settings drinks will not effect other groups than the "beverage"-group with seperate effects from other groups, so I think this way it's possible to implement a balanced system including drinks: So drinking a lot will not be honored, but drinking too less will be punished with nausea and slower movement (so default_value is 0.5). Furthermore keeping beverage-level over a level of 0.6 will be nessessary too for the "all"-two-heart-benefit, so this way it makes it tougher, i think. I even think of punishing too much drinking too, so only a balncend drinking behaviour will be rewarded...

btw.. I died and got nausea on respawn.. Maybe the values are all set to 0.0 on death instead of default_value..   I'll test it and report a bug in case..

**Comment by TheIllusiveC4** [comment]
> and, no offence,.. Diet supports Simply-Tea-Mod, where you can drink infinitely any cup of tea, so..

This is a bug that I'll fix soon.

> btw.. I died and got nausea on respawn.. Is it intended that the values are all set to 0.0 on death instead of default_value?

Yes, because you need to configure the death penalty loss. However, I'll add an updated config that has the ability to reset the diet values to their defaults instead of applying a death penalty.

**Comment by Sonanndes** [comment]
That's nice.
Gave up to establish a workaround for beverages.. but using Diet as it is. Great work.
