### ISSUE TITLE
Update Autumnity and Bloom and Gloom Support

### ISSUE THREAD

**Issue by NJL5390** [TheIllusiveC4/Diet#26]
These two mods already have support from your mod but they got updates recently to add more foods. It would be great if support for these mods could be updated to match it. 

- Autumnity: https://www.curseforge.com/minecraft/mc-mods/autumnity
- Bloom and Gloom: https://www.curseforge.com/minecraft/mc-mods/bloom-and-gloom

Thanks in advance!

**Comment by TheIllusiveC4** [comment]
Can you list the foods that were added? That would just help me make sure that I don't miss anything.

**Comment by NJL5390** [comment]
I can do that yes, I'll do it later on when I'm not busy.

**Comment by NJL5390** [comment]
Ok, So here's the foods that I could find using JEI that haven't been assigned any nutrition values yet:

- Fairy ring mushroom stew (bloom_and_gloom:fairy_ring_mushroom_stew)
- Roasted Cactus (bloom_and_gloom:roasted_cactus)
- Candied Kabloom Fruit (bloom_and_gloom:candied_kabloom_fruit)
- Foul Soup (autumnity:foul_soup)
