### ISSUE TITLE
Client /server sync problem??

### ISSUE THREAD

**Issue by zanecek** [TheIllusiveC4/Diet#28]
Hi. Nice mod, but i have a problem:
When I right click with armor in main hand, it move to armor slot (armor hotswap function) just "a little".
Armor is displayed in the armor slot, but does not work (it is not damaged during the attack) and when I click in inventory on its armor slot or the hotbar original slot, it immediately returns to the hotbar.

Without diet its works good, without quark its works good.

- minecraft 1.16.5
- forge 36.1.0
- armor hotswap 1.4 ( https://www.curseforge.com/minecraft/mc-mods/armor-hotswap )
- quark r2.4-308 + autoreglib 1.6-47
- diet 0.18
- no other mods

**Comment by TheIllusiveC4** [comment]
I'm not really sure what's going on here, but Diet doesn't do anything with armor or inventories. It's more likely the culprit is either Quark or Armor Hotswap.

**Comment by zanecek** [comment]
Yes, you are right, sorry, the problem is armor hotswap mod itself (sometimes).
I don't know why the problem appeared after adding your mod and disappeared after removing it - probably some side effect.
