### ISSUE TITLE
lesser %?

### ISSUE THREAD

**Issue by Tomasaa3** [TheIllusiveC4/Diet#39]
it always acticate the effect in 80% how do you make it activate at 50% ?, srry if it is explained i didn't understand it, i'm learning english
i tried changing the value of "above" by "0.5" but it still need to get 80% to give the effect, i just tried eating only carrots and changed all the "above" values by 0.5 not only one

**Comment by TheIllusiveC4** [comment]
Share your config files.

**Comment by Tomasaa3** [comment]
[defaultconfigs.zip](https://github.com/TheIllusiveC4/Diet/files/6290613/defaultconfigs.zip)

**Comment by TheIllusiveC4** [comment]
Unfortunately, I cannot reproduce your issue. I copied your configs exactly and they work as you wanted. Getting any diet group above 50% will trigger one of the effects, without needing to get to 80%.
