### ISSUE TITLE
Support for Spice of Life: Potato edition's Lunchbags and Lunchboxes

### ISSUE THREAD

**Issue by NJL5390** [TheIllusiveC4/Diet#4]
Hi,
I've been using a mod recently called Spice of Life: Potato edition which adds Lunchbags and Lunchboxes that you can store food in and eat food out of by using the lunchbox / lunchbag. (https://www.curseforge.com/minecraft/mc-mods/spice-of-life-potato-edition)
![2021-02-18_18 07 43](https://user-images.githubusercontent.com/64381954/108402402-5d4ae080-7215-11eb-8899-25141aa62ddd.png)
![2021-02-18_18 08 04](https://user-images.githubusercontent.com/64381954/108402424-6936a280-7215-11eb-8212-51b7d987164a.png)
![2021-02-18_18 36 07](https://user-images.githubusercontent.com/64381954/108405107-99cc0b80-7218-11eb-9c47-984818e84a38.png)
![2021-02-18_18 36 20](https://user-images.githubusercontent.com/64381954/108405134-a05a8300-7218-11eb-8978-12f47d73c793.png)

However, Whenever food is eaten from these items Diet doesn't register it and therefore nutrition values do not increase despite the food having been consumed from the lunchbox. I'm not sure if this is something that would need done on their end so let me know if that is the case. 

I have no idea how easy this would be to accomplish (which is why I made this a separate issue) so I don't mind if this is something that takes a long time to do. This isn't an urgent issue, especially since you can get around this issue by taking the food item out of the lunchbox before eating it. This is just something to think about doing for the future.

Thanks!

(Edit: I've now posted this issue in their github: https://github.com/Kevun1/Spice-of-Life-Potato-Edition/issues/14)

**Comment by NJL5390** [comment]
Just thought I'd give you one of my logs in case it helps: https://pastebin.com/RyXL2zzi

**Comment by TheIllusiveC4** [comment]
I made a PR to SOL: Potato to help address this issue:
https://github.com/Kevun1/Spice-of-Life-Potato-Edition/pull/15

**Comment by NJL5390** [comment]
Sweet! Thanks a lot!

**Comment by TheIllusiveC4** [comment]
Unfortunately it seems that SoL: Potato Edition has not been updated in a while and the PR needed to accomplish this compatibility is in indefinite limbo. I'll be closing this issue due to a lack of foreseeable progress in the context of this repository, but anyone interested can simply follow that PR on the SoL: Potato Edition repository to see if it ever gets merged.
