### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pwigary** [TheIllusiveC4/Diet#45]
How could user change the default group name so it got display on the food an in GUI. ie from protein to meat, vegetables to veggies?

**Comment by TheIllusiveC4** [comment]
Add your own `en_us.json` localization file with your own entries. I believe yours would then be able to override the default ones. This is the default file for reference:
https://github.com/TheIllusiveC4/Diet/blob/main/src/main/resources/assets/diet/lang/en_us.json
