### ISSUE TITLE
My Diet just "reseted?"

### ISSUE THREAD

**Issue by TwiceVeryHappy** [TheIllusiveC4/Diet#46]
I was playing on a multiplayer server, when I realized this, I closed the game, disconnected and killed myself, and nothing happens! even if I eat something 
![image](https://user-images.githubusercontent.com/85046764/120091158-cd9fb280-c0de-11eb-8db4-b39cfde4e565.png)

**Comment by TheIllusiveC4** [comment]
It looks like something de-activated your diet. Can you reproduce this in a single-player world? Otherwise, it seems like a mod or a server operator did this manually.

**Comment by TwiceVeryHappy** [comment]
thanks, I took a look at the commands on your mod and ended up discovering the problem, I think that when we made some settings we must have been wrong
![image](https://user-images.githubusercontent.com/85046764/120117093-eef5b280-c161-11eb-9098-584ede77e2ef.png)
