### ISSUE TITLE
Suggestion: Change how the diet window functions to be more similar to the recipe book

### ISSUE THREAD

**Issue by Foozey** [TheIllusiveC4/Diet#47]
You should be able to close the window again easily with a button to go back to the inventory view, just like how the recipe book works. Or better yet, make it so the inventory is still visible while you bring up the window, just like how the recipe book and curios window works. It's not the best user experience having to press escape to close the window and fully exit out of everything.

**Comment by TheIllusiveC4** [comment]
Currently, if you press the inventory button again from the Diet screen, you can go directly back to the inventory screen. Isn't that what you're asking for?

As for making it so that you can see your inventory too, the reason this is difficult is because the Diet screen is large enough that it would cover the whole inventory screen and it'd be a tight fit to try and fit both on one screen. In addition, it makes sense to see the inventory with the recipe book and Curios because those require information from your inventory for crafting and moving items to the Curios slots respectively. What purpose is there to see your inventory while looking at your Diet information?

**Comment by Foozey** [comment]
I just mean to return to the inventory screen, it would be more user friendly to still have a visible button on-screen somewhere to press, rather than having to press a "hidden" keybind. Maybe you could switch it from a button to a tab of sorts, where if you press the tab, it switches from inventory view to diet view, then you can go back to the inventory tab. That could look nice, and it would be vanilla friendly as it would act similar to creative mode tabs.

**Comment by Foozey** [comment]
Going back to this, after some testing, I do think the tab would be the best solution for user experience. Having the button is definitely much better than what it was before, and I'm perfectly happy if you decide to ignore this and just go with the button. But recently I've been messing around with [Rereskillable](https://www.curseforge.com/minecraft/mc-mods/rereskillable) which uses a tab for its window, and it really does feel nice as a user. It feels really natural having a tab for something that's an extension of the player like the skills window in Rereskillable or the dietary effects window in Diet. If you get the chance, do a little bit of testing with this yourself, and see what you like best.

**Comment by Foozey** [comment]
One thing I'll note though, is that Rereskillable's skills window matches the size of the vanilla inventory, which I'm sure contributes to why it feels so smooth. It might be possible to make the Diet window match the inventory at least in width. However, I'm not sure if it will be possible to get a good looking design that way. I might make a mockup for you and send it to you either through here or discord. If you like the mockup, you'll at least have a reference for how you can implement it.

**Comment by TheIllusiveC4** [comment]
The biggest problem with this isn't that I don't think it'd be a good user experience, it's that adding a tab makes it more incompatible with other mods. Imagine a bunch of mods want to add a tab to the inventory, how do they do so without needing to hardcode compatibility with every other mod that tries to do that? It'd be a different case if Forge provided a common API for such a thing, but something like that is not currently present.
