### ISSUE TITLE
Unsure if intentional: JEI is hidden while Diet GUI is open

### ISSUE THREAD

**Issue by Foozey** [TheIllusiveC4/Diet#49]
Is it JEI's side, or this Diet's side that does this?

**Comment by TheIllusiveC4** [comment]
I'm not sure. Is there an instance where JEI is visible on a GUI that isn't a container or inventory? If there isn't, then probably intentional as the Diet GUI is neither of those.

**Comment by Foozey** [comment]
Happy to test now, got any examples? I can't think of any.

**Comment by TheIllusiveC4** [comment]
I can't think of any either. I did test with the Nutrition mod for 1.12.2 with JEI since the GUI is similar and that one doesn't show JEI with it either. So until shown otherwise, I'll go ahead and label this as behaving as expected.

**Comment by Foozey** [comment]
Just thought I'd mention, this also happens with [rereskillable](https://github.com/majikdev/rereskillable). In their language file they label the skills window as a `container`, but I'm not sure if it actually is? It functions similar to how your diet window functions. Regardless, neither of these issues are of much importance, there's no benefit to having JEI open while either of these windows are active.
