### ISSUE TITLE
[Request] Config Option for Starting+Death Diet %

### ISSUE THREAD

**Issue by Sakonas** [TheIllusiveC4/Diet#52]
Similar to the Nutrition mod for 1.12, it would be great to have the option to change the starting % to allow for negative player effects upon falling below a certain % threshold. Additionally, having a % penalty on death would introduce a bit of balance for the added % upon starting a new world and overall add a bit of difficulty and benefit to maintaining the diet group values.

**Comment by TheIllusiveC4** [comment]
I believe what you want already exists, unless I'm missing something.

1) You can set the starting % of each diet group. Go into `diet-groups.toml` in the `serverconfigs` and edit the `default_value` field to the percentage that you want.

2) You can set the percentage death penalty. Go into `diet-server.toml` in the `serverconfigs` and edit the death penalty values to whatever you want.
