### ISSUE TITLE
Request: Make UI text colour configurable

### ISSUE THREAD

**Issue by COLDW0LF** [TheIllusiveC4/Diet#57]
As title suggests; I'm working on a dark GUI for a modpack, and the text on the main Diet GUI is almost invisible!
It'd be great to be able to change the colour of the text in the configs, to match other GUI re-textures.

**Comment by TheIllusiveC4** [comment]
You already can in the `diet-groups.toml` configs as described here:
https://github.com/TheIllusiveC4/Diet/wiki/Customizing-Food-Groups

There's a `color` field for each group.

**Comment by COLDW0LF** [comment]
Good lord, I'm blind! I thought that was for JEI tooltips. *facepalm*
Thanks for the heads up!

**Comment by COLDW0LF** [comment]
Actually, hold up... it's the TEXT I'm talking about, as in the names of the groups.
I know the bars and percentages can be colored, but the names of the groups aren't, correct?

**Comment by TheIllusiveC4** [comment]
Ahhh, I see what you mean now. Okay, duly noted, I'll see what I can do.

**Comment by COLDW0LF** [comment]
Ah, cracked it! The en_us.json accepts the §x§y color codes, was able to do it in there easily.
You can probably close this, unless it's something you'd want to implement otherwise.
Thanks! :)

**Comment by TheIllusiveC4** [comment]
I added a config option for it.

**Comment by COLDW0LF** [comment]
Haha, already?! Fantastic, thank you so much!
