### ISSUE TITLE
Food blocks (like cake) don't apply any food group increase

### ISSUE THREAD

**Issue by SodiumShine** [TheIllusiveC4/Diet#6]
Both Minecraft cakes and Cooked Turkey from Better Animals Plus don't seem to function with Diet, despite both being tagged and cake having a 5.5% increase for sugar levels.

**Comment by TheIllusiveC4** [comment]
By cakes do you mean modded cakes or `minecraft:cake`? Because the regular cake should work natively. However, modded edible blocks will need specific integration.

**Comment by SodiumShine** [comment]
I mean `minecraft:cake` yes. The one you place on the ground and eat it by right-clicking the block.

**Comment by SodiumShine** [comment]
WAIT, I just realised the problem. I have another mod that has overwritten the block itself.

`supplementaries:directional_cake`

My bad.
