### ISSUE TITLE
Pams Harvestcraft 2 corn

### ISSUE THREAD

**Issue by s10w10rr1s** [TheIllusiveC4/Diet#63]
Corn has no nutritional value. Cornmeal gives vegetables and for some reason a tortilla gives you an insane amount of protein.

**Comment by TheIllusiveC4** [comment]
Can you split your suggestion into what you see in the mod right now and what you expect?

**Observed Behavior**:

**Expected Behavior**:

**Comment by s10w10rr1s** [comment]
Observed Behavior: Cornmeal provides vegetables. Tortilla provides proteins

Expected Behavior: Cornmeal provides grains or nothing at all (cause its raw cornmeal). Tortilla provides grains
