### ISSUE TITLE
[Enhancement/suggestion] Cross Compat and default values for Blue skies

### ISSUE THREAD

**Issue by Darkmega18** [TheIllusiveC4/Diet#64]
Blue skies recently came out and it has a various berries and meats etc that don't gain default values it seems, since it's a recently updated mod. Some default values could be added to the foods.

Along with blue skies, it also has a food prep table that allows you to combine multiple foods together, similar probably to the culinary construct mod, but with something about being able to food prep potions or plants into the meals to give them buffs. Basically, I just hope you can figure out a way to make their prep table carry over the dietary benefits of given foods placed in it.

**Comment by TheIllusiveC4** [comment]
I can tag the basic foods that the mod adds, but anything more complicated like composite foods will need integration from their end.

**Comment by Darkmega18** [comment]
Roger that. I'll leave them a suggestion I guess.
