### ISSUE TITLE
[Suggestion] A way to specify the exact amount of nutrition something gives

### ISSUE THREAD

**Issue by vizthex123** [TheIllusiveC4/Diet#68]
Title. It'd be nice to have precise control over specific items.

**Comment by TheIllusiveC4** [comment]
This already exists, using the `foodOverrides` list to override the existing values with a new one.

**Comment by vizthex123** [comment]
Hmmm...… I haven't seen anything like that on the wiki. What's the exact method to do this?

**Comment by TheIllusiveC4** [comment]
The wiki doesn't outline the basic configs in the `diet-server.toml` file, where the list is located.

**Comment by vizthex123** [comment]
Yeah, I found it eventually. Could you add info about it to the wiki?

**Comment by TheIllusiveC4** [comment]
What info would you like to be added to the wiki? Each config value has comments in the file itself that describe what the value is used for, so I'm not sure what I could add to the wiki that wouldn't be redundant.

**Comment by vizthex123** [comment]
It's more just informing people it exists (maybe on a config page or home page perhaps?)

**Comment by TheIllusiveC4** [comment]
Okay, I've added a brief mention of all the configuration files on the home page which should help notify people that the file exists.

**Comment by vizthex123** [comment]
Noice, thanks.
