### ISSUE TITLE
[Suggestion] Atum food level restoration values

### ISSUE THREAD

**Issue by Darkmega18** [TheIllusiveC4/Diet#69]
What it says on the tin.
heres a list of what I found that needs adding to.

atum:emmer_bread
atum:camel
atum:camel_cooked
atum:quail
atum:quail_cooked
atum:date
atum:glistering_date
atum:golden_date
atum:golden_date_enchanted
atum:crunchy_scarab
atum:crunchy_golden_scarab

also, is there a way to add values via a json file or perhaps a string array like:
_**mod:name, group, percentage**_
group being the name of the food group in the food group config.
percentage being a number between 0 and 100.

probably a server config list or another file in a common file in the config folder somewhere to do custom values for people who end up with mods that don't have values built in already or want to hard customize/rebalance?

**Comment by TheIllusiveC4** [comment]
> also, is there a way to add values via a json file or perhaps a string array like:

Yes. Groups are determined by tags. So just make a datapack and tag items with the appropriate groups. For instance, adding anything to a fruits group would be tagged as `diet:fruits`.

Overriding the food values used for diet gain is done by using the `foodOverrides` array in the `diet-server.toml` file.

**Comment by Darkmega18** [comment]
oh, so it's two fold? does adding the tag to it just make the percentage appear based on how powerful the food is and divided by the different groups or something?

**Comment by TheIllusiveC4** [comment]
Yes, the calculations are based off of a "quality" value, which is normally (food gain + (food gain * saturation modifier)). It's not strictly divided by different groups, as there's a penalty deducted for each group it's added to (this penalty is configurable in `diet-server.toml` as well). The override list can be used to offer another "quality" value instead to any particular item.

**Comment by Darkmega18** [comment]
roger-roger. I'll go do that then.
