### ISSUE TITLE
Server Crashes on startup when attempting to use this mod on a dedicated server

### ISSUE THREAD

**Issue by NJL5390** [TheIllusiveC4/Diet#7]
Minecraft Version: 1.16.5
Forge Version: 36.0.42
Diet Version: 0.2

Whenever I attempt to use this mod on my dedicated server, the server just crashes on startup, Therefore preventing me from using this mod in a multiplayer environment.

Latest Log: https://pastebin.com/qtB0Ljnd
Crash Report: https://pastebin.com/PSh5JCDX

**Comment by TheIllusiveC4** [comment]
Hm, very strange. I thought I fixed this. Also, I can't replicate this on my instances which makes this harder to solve.

I've made an attempted fix, can you try out the test version below and see if it resolves your issue?

[diet-forge-1.16.5-0.3-SNAPSHOT.zip](https://github.com/TheIllusiveC4/Diet/files/6013119/diet-forge-1.16.5-0.3-SNAPSHOT.zip)

If it still crashes, send me the crash report again but also include the `debug.log` log file.

**Comment by NJL5390** [comment]
Yeah, That did the trick. It's all fixed!

One thing I will mention is that when initially loading up this version, my client crashed, after deleting diet's config files and letting them regenerate with this new version everything was fine after that.  So it might be a good idea to ask people to delete and regenerate their config files when updating to this version.

**Comment by TheIllusiveC4** [comment]
That's strange. Do you have the crash log for the client crash?

**Comment by NJL5390** [comment]
Yep, here you go: https://pastebin.com/YsUE0qvT

Only happened once and it has not happened since, again after deleting my old diet config files and letting them regenerate with the new version  the issue seemed to fix itself.

**Comment by TheIllusiveC4** [comment]
Hmm, that seems to have occurred because `repurposed_structures-temples.toml` was being used by another process while you were starting the game. It doesn't seem related to Diet, so I think the crash was just a coincidence. However, I'll keep this in mind in case this issue comes up again.

**Comment by NJL5390** [comment]
> Hmm, that seems to have occurred because `repurposed_structures-temples.toml` was being used by another process while you were starting the game. It doesn't seem related to Diet, so I think the crash was just a coincidence. However, I'll keep this in mind in case this issue comes up again.

Yeah, I've had similar crashes randomly occur in the past only to have them never appear ever again and this seems like it was just one of those.

Thanks for your help with this issue!
