### ISSUE TITLE
[Suggestion] The ability to reduce attributes using dietary effects

### ISSUE THREAD

**Issue by vizthex123** [TheIllusiveC4/Diet#70]
Say, removing 4 Max Health if everything is below 50%, or what have you. Then gaining it back when the nutrient(s) go above the threshold.

Would it be possible to add this?

**Comment by TheIllusiveC4** [comment]
This already exists, just use negative numbers for the amount values.

**Comment by vizthex123** [comment]
Interesting. I don't remember the wiki saying this, mind updating it?

**Comment by TheIllusiveC4** [comment]
The wiki says this:
```
amount - decimal

The amount to use for the operation on the attribute modifier
```

It doesn't say that the number has to be positive.

**Comment by vizthex123** [comment]
Well, I just assumed it would kill itself if I used a negative number lol.
