### ISSUE TITLE
[Suggestion] Config option to disable nutrient reset on death

### ISSUE THREAD

**Issue by vizthex123** [TheIllusiveC4/Diet#71]
I've added a few negative effects to my pack, but I noticed that all the nutrients get set to 0 when you die. Can you add a config option to disable this?

**Comment by TheIllusiveC4** [comment]
This already exists. Either you change the `default_value` for the groups in the `diet-groups.toml` file to a different value that it will reset to, or you change the death penalty values in `diet-server.toml` (`deathPenaltyLoss`, `deathPenaltyMin`, `deathPenaltyMethod`).

**Comment by vizthex123** [comment]
Yeah, I found it. Thought I'd said so here. Could you update the wiki with this?

**Comment by TheIllusiveC4** [comment]
What would you like to be updated on the wiki? The `default_value` value for `diet-groups.toml` is mentioned on its respective page, and the config file for `diet-server.toml` has comments for each of its own values.
