### ISSUE TITLE
[Suggestion] Toggle options

### ISSUE THREAD

**Issue by Omni-MC** [TheIllusiveC4/Diet#73]
Would love to be able to toggle the compat for each mod and to toggle the tooltips.
Does not fit the title but I feel having little icons rather than text in the tooltip would feel a little more immersive.

**Comment by TheIllusiveC4** [comment]
I don't understand what you mean by toggling the compat and tooltips. You'll have to be more specific.

As for icons in the tooltip, I'm trying to match vanilla's attribute tooltips where it says +1 Armor and such. I don't think it'd match the aesthetic of vanilla if I changed the tooltip to icons.
