### ISSUE TITLE
[Suggestion] Hide diet properties until first eaten

### ISSUE THREAD

**Issue by IchHabeHunger54** [TheIllusiveC4/Diet#85]
I would appreciate an option that hides diet properties for an item until the player has eaten it.
Don't know how probable that is to happen, as I imagine it being rather hard to implement, but I would appreciate it. Would play well with hardcore-realistic packs.

**Comment by TheIllusiveC4** [comment]
Hmm, probably not _that_ hard. I'll implement it if it's at all feasible.
