### ISSUE TITLE
[Feature]: Command to log ungrouped food

### ISSUE THREAD

**Issue by Boolyman** [TheIllusiveC4/Diet#89]
### What is the new feature or improvement?

One suggestion that I saw in a similar mod (Nutritional Balance) was the ability to run a command to log/list all foods that aren't currently assigned a food group.  Would really help with setting up custom groups.

**Comment by TheIllusiveC4** [comment]
This is already in the mod but I just realized that I never wrote any documentation for them. I've written them up now and you can see it here:
https://github.com/TheIllusiveC4/Diet/wiki/Commands#diet-export-uncategorized

Basically you can just use `/diet export uncategorized` and you'll get a list of unassigned foods in a `logs/diet.csv` file. There are also other export types if you're interested.

**Comment by Boolyman** [comment]
Thank you!
