### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Boolyman** [TheIllusiveC4/Diet#92]
### What happened?

I set up new groups and effects, but I am getting a crash when the world generates.  The log references an issue with the diet-effects config.  I have inlcluded the paste.gg of the log below.  I'm thinking maybe I used an operation that wasn't appropriate for the effect attribute I was trying to increase, or something?

### How do you trigger this bug?

1.
2.
3.
...

### Forge Version

Forge - 36.2.8

### Mod Version

diet-forge-1.16.5-1.0.0.jar

### Relevant Log Outputs

diet-effects file: https://paste.gg/p/anonymous/aced9e5798384e1184db6a0bae62f4ba

Log error:  https://paste.gg/p/anonymous/d7dc3c91f64b49cd85ce4c51c5d8aeca

**Comment by TheIllusiveC4** [comment]
I just realized that it actually has to be this way because I'm not the one casting it, the config system is. Oh well, I'll just have to keep this in mind for the future in case other people have this issue.
