### ISSUE TITLE
[Five Food Groups]: Create Confectionery - VERY SUGARY

### ISSUE THREAD

**Issue by PixVoxel** [TheIllusiveC4/Diet#93]
### If applicable, which other mod(s) is/are involved in your request?

[Create Confectionery]https://www.curseforge.com/minecraft/mc-mods/create-confectionery

### What is the new support or change you're requesting?

I'm requesting these foods to add five food groups.
create_confectionery:bar_of_black_chocolate
create_confectionery:bar_of_white_chocolate
create_confectionery:bar_of_ruby_chocolate
create_confectionery:bar_of_caramel
create_confectionery:black_chocolate_glazed_berries
create_confectionery:white_chocolate_glazed_berries
create_confectionery:ruby_chocolate_glazed_berries
create_confectionery:caramel_glazed_berries
create_confectionery:marshmallow
create_confectionery:chocolate_glazed_marshmallow
create_confectionery:black_chocolate_glazed_marshmallow
create_confectionery:white_chocolate_glazed_marshmallow
create_confectionery:ruby_chocolate_glazed_marshmallow
create_confectionery:marshmallow_on_a_stick
create_confectionery:caramelized_marshmallow_on_a_stick
create_confectionery:honey_candy
create_confectionery:hot_chocolate_bottle
create_confectionery:soothing_hot_chocolate
create_confectionery:chocolate_candy
create_confectionery:chocolate_candy_1
create_confectionery:chocolate_candy_2
create_confectionery:chocolate_candy_3
create_confectionery:black_chocolate_candy
create_confectionery:black_chocolate_candy_1
create_confectionery:black_chocolate_candy_2
create_confectionery:black_chocolate_candy_3
create_confectionery:white_chocolate_candy
create_confectionery:white_chocolate_candy_1
create_confectionery:white_chocolate_candy_2
create_confectionery:white_chocolate_candy_3
create_confectionery:ruby_chocolate_candy
create_confectionery:ruby_chocolate_candy_1
create_confectionery:ruby_chocolate_candy_2
create_confectionery:ruby_chocolate_candy_3

**Comment by xilleto** [comment]
These foods are not recognized as sugar foods

create_confectionery:bar_of_black_chocolate
create_confectionery:bar_of_white_chocolate
create_confectionery:bar_of_ruby_chocolate
create_confectionery:bar_of_caramel
