### ISSUE TITLE
Inconsistencies in farmer's delight

### ISSUE THREAD

**Issue by megagnarxd** [TheIllusiveC4/Diet#99]
### What is the new feature or improvement?

I will update the list as I go. But for now:

grilled salmon--doesn't have protein
baked cod stew--doesn't have protein

and generally food tends to lose it's nutritional benefits when crafted.

To resolve this, tweak the base food properties. Let meat have lower protein % and so on
and to compensate for the decrease in nutritional benefits, you should lower the time taken for the nutritional benefits to decline

**Comment by TheIllusiveC4** [comment]
I am not seeing the same thing, with only Diet and Farmer's Delight installed the Grilled Salmon and Baked Cod Stew have Proteins. Can you reproduce the listed inconsistencies with only those two mods installed? If not, it could be a mod conflict or a datapack error.
